enum TrainingGoal {
  buildMuscle('Build muscle', 'Hypertrophy-focused strength work'),
  getStronger('Get stronger', 'Practice the main movement patterns'),
  loseWeight('Lose weight', 'Higher-tempo full-body sessions'),
  improveFitness('Improve fitness', 'Balanced strength and conditioning'),
  mobility('Move better', 'Mobility and recovery work');

  const TrainingGoal(this.label, this.description);

  final String label;
  final String description;
}

class ExerciseGuide {
  const ExerciseGuide({
    required this.id,
    required this.name,
    required this.level,
    required this.equipment,
    required this.primaryMuscle,
    required this.secondaryMuscles,
    required this.instructions,
    required this.imagePaths,
    required this.goals,
    required this.defaultSets,
    required this.defaultReps,
    required this.restSeconds,
    this.movementPattern = 'General',
    this.variationGroup,
    this.coachingCues = const [],
    this.commonMistakes = const [],
  });

  static const _sourceRoot =
      'https://raw.githubusercontent.com/yuhonas/free-exercise-db/'
      'b0eed061e1c832b3ed815fbaa4b45b3cdc14df49/exercises';

  final String id;
  final String name;
  final String level;
  final String equipment;
  final String primaryMuscle;
  final List<String> secondaryMuscles;
  final List<String> instructions;
  final List<String> imagePaths;
  final Set<TrainingGoal> goals;
  final int defaultSets;
  final String defaultReps;
  final int restSeconds;
  final String movementPattern;
  final String? variationGroup;
  final List<String> coachingCues;
  final List<String> commonMistakes;

  List<String> get imageUrls =>
      imagePaths.map((path) => '$_sourceRoot/$path').toList(growable: false);
}

const exerciseGuides = <ExerciseGuide>[
  ExerciseGuide(
    id: 'Pushups',
    name: 'Push-ups',
    level: 'Beginner',
    equipment: 'Bodyweight',
    primaryMuscle: 'Chest',
    secondaryMuscles: ['Shoulders', 'Triceps'],
    instructions: [
      'Start in a strong plank with hands slightly wider than your shoulders.',
      'Lower under control until your chest is close to the floor.',
      'Press the floor away while keeping your hips and shoulders moving together.',
    ],
    imagePaths: ['Pushups/0.jpg', 'Pushups/1.jpg'],
    goals: {
      TrainingGoal.buildMuscle,
      TrainingGoal.loseWeight,
      TrainingGoal.improveFitness,
    },
    defaultSets: 3,
    defaultReps: '8–15 reps',
    restSeconds: 60,
    movementPattern: 'Horizontal push',
    variationGroup: 'chest-press',
    coachingCues: ['Brace your core', 'Move as one solid line'],
    commonMistakes: ['Flaring elbows excessively', 'Letting the hips sag'],
  ),
  ExerciseGuide(
    id: 'Barbell_Bench_Press_-_Medium_Grip',
    name: 'Barbell bench press',
    level: 'Beginner',
    equipment: 'Barbell and bench',
    primaryMuscle: 'Chest',
    secondaryMuscles: ['Shoulders', 'Triceps'],
    instructions: [
      'Lie on the bench with feet planted and use a secure medium-width grip.',
      'Lower the bar slowly toward the middle of your chest.',
      'Press upward with control. Use a spotter or safety arms for challenging loads.',
    ],
    imagePaths: [
      'Barbell_Bench_Press_-_Medium_Grip/0.jpg',
      'Barbell_Bench_Press_-_Medium_Grip/1.jpg',
    ],
    goals: {TrainingGoal.buildMuscle, TrainingGoal.getStronger},
    defaultSets: 3,
    defaultReps: '6–10 reps',
    restSeconds: 90,
    movementPattern: 'Horizontal push',
    variationGroup: 'chest-press',
    coachingCues: ['Keep feet planted', 'Keep wrists stacked over elbows'],
    commonMistakes: [
      'Bouncing the bar',
      'Lifting without safeties or a spotter',
    ],
  ),
  ExerciseGuide(
    id: 'Barbell_Full_Squat',
    name: 'Barbell squat',
    level: 'Intermediate',
    equipment: 'Barbell and squat rack',
    primaryMuscle: 'Quadriceps',
    secondaryMuscles: ['Glutes', 'Hamstrings', 'Calves'],
    instructions: [
      'Set the rack and safety arms before loading the bar.',
      'Brace your trunk, sit the hips down and back, and keep your feet planted.',
      'Stand by driving through the whole foot while keeping the bar controlled.',
    ],
    imagePaths: ['Barbell_Full_Squat/0.jpg', 'Barbell_Full_Squat/1.jpg'],
    goals: {
      TrainingGoal.buildMuscle,
      TrainingGoal.getStronger,
      TrainingGoal.improveFitness,
    },
    defaultSets: 3,
    defaultReps: '6–10 reps',
    restSeconds: 120,
    movementPattern: 'Squat',
    variationGroup: 'squat',
    coachingCues: [
      'Brace before descending',
      'Keep pressure through the whole foot',
    ],
    commonMistakes: ['Knees collapsing inward', 'Losing trunk position'],
  ),
  ExerciseGuide(
    id: 'Bent_Over_Barbell_Row',
    name: 'Bent-over barbell row',
    level: 'Beginner',
    equipment: 'Barbell',
    primaryMuscle: 'Back',
    secondaryMuscles: ['Lats', 'Biceps', 'Shoulders'],
    instructions: [
      'Hinge at the hips with soft knees and keep your back braced.',
      'Pull the bar toward your torso while keeping your elbows controlled.',
      'Pause briefly, then lower the bar without changing torso position.',
    ],
    imagePaths: ['Bent_Over_Barbell_Row/0.jpg', 'Bent_Over_Barbell_Row/1.jpg'],
    goals: {TrainingGoal.buildMuscle, TrainingGoal.getStronger},
    defaultSets: 3,
    defaultReps: '8–12 reps',
    restSeconds: 90,
    movementPattern: 'Horizontal pull',
    variationGroup: 'horizontal-pull',
    coachingCues: ['Keep the bar close', 'Pull elbows behind you'],
    commonMistakes: ['Jerking the torso', 'Rounding the lower back'],
  ),
  ExerciseGuide(
    id: 'Dumbbell_Lunges',
    name: 'Dumbbell lunges',
    level: 'Beginner',
    equipment: 'Dumbbells',
    primaryMuscle: 'Quadriceps',
    secondaryMuscles: ['Glutes', 'Hamstrings', 'Calves'],
    instructions: [
      'Stand tall with a dumbbell at each side.',
      'Step forward and lower with control while maintaining balance.',
      'Push through the front foot to return, then repeat on the other side.',
    ],
    imagePaths: ['Dumbbell_Lunges/0.jpg', 'Dumbbell_Lunges/1.jpg'],
    goals: {
      TrainingGoal.buildMuscle,
      TrainingGoal.loseWeight,
      TrainingGoal.improveFitness,
    },
    defaultSets: 3,
    defaultReps: '8–12 / side',
    restSeconds: 60,
    movementPattern: 'Lunge',
    variationGroup: 'lunge',
    coachingCues: ['Stay tall', 'Control the front knee'],
    commonMistakes: [
      'Taking an unstable narrow step',
      'Pushing only from the toes',
    ],
  ),
  ExerciseGuide(
    id: 'Pullups',
    name: 'Pull-ups',
    level: 'Beginner',
    equipment: 'Pull-up bar',
    primaryMuscle: 'Lats',
    secondaryMuscles: ['Biceps', 'Back'],
    instructions: [
      'Hang from the bar with a grip you can control.',
      'Pull your shoulders down and bring your upper chest toward the bar.',
      'Lower slowly to full arm extension without dropping into the bottom.',
    ],
    imagePaths: ['Pullups/0.jpg', 'Pullups/1.jpg'],
    goals: {TrainingGoal.buildMuscle, TrainingGoal.getStronger},
    defaultSets: 3,
    defaultReps: '5–10 reps',
    restSeconds: 90,
    movementPattern: 'Vertical pull',
    variationGroup: 'vertical-pull',
    coachingCues: ['Start by lowering the shoulders', 'Keep the swing minimal'],
    commonMistakes: ['Kipping unintentionally', 'Dropping out of the bottom'],
  ),
  ExerciseGuide(
    id: 'Plank',
    name: 'Plank',
    level: 'Beginner',
    equipment: 'Bodyweight',
    primaryMuscle: 'Core',
    secondaryMuscles: [],
    instructions: [
      'Support yourself on your forearms and toes with elbows below shoulders.',
      'Keep a straight line from head to heels and breathe normally.',
      'End the set when you can no longer hold the position cleanly.',
    ],
    imagePaths: ['Plank/0.jpg', 'Plank/1.jpg'],
    goals: {
      TrainingGoal.loseWeight,
      TrainingGoal.improveFitness,
      TrainingGoal.mobility,
    },
    defaultSets: 3,
    defaultReps: '20–45 sec',
    restSeconds: 45,
    movementPattern: 'Core stability',
    variationGroup: 'core-stability',
    coachingCues: ['Squeeze glutes gently', 'Breathe behind the brace'],
    commonMistakes: ['Holding the breath', 'Letting the lower back sag'],
  ),
  ExerciseGuide(
    id: 'Mountain_Climbers',
    name: 'Mountain climbers',
    level: 'Beginner',
    equipment: 'Bodyweight',
    primaryMuscle: 'Full body',
    secondaryMuscles: ['Quadriceps', 'Chest', 'Shoulders'],
    instructions: [
      'Begin in a stable push-up position.',
      'Bring one knee toward the hip while keeping your hands planted.',
      'Alternate legs at a pace that lets you maintain a steady trunk.',
    ],
    imagePaths: ['Mountain_Climbers/0.jpg', 'Mountain_Climbers/1.jpg'],
    goals: {TrainingGoal.loseWeight, TrainingGoal.improveFitness},
    defaultSets: 3,
    defaultReps: '20–30 sec',
    restSeconds: 45,
    movementPattern: 'Conditioning',
    variationGroup: 'conditioning',
    coachingCues: ['Keep shoulders over hands', 'Choose a sustainable rhythm'],
    commonMistakes: [
      'Bouncing the hips high',
      'Moving faster than you can control',
    ],
  ),
  ExerciseGuide(
    id: 'Romanian_Deadlift',
    name: 'Romanian deadlift',
    level: 'Intermediate',
    equipment: 'Barbell',
    primaryMuscle: 'Hamstrings',
    secondaryMuscles: ['Glutes', 'Lower back'],
    instructions: [
      'Hold the bar close to your legs with knees slightly bent.',
      'Push your hips back while keeping your trunk braced and the bar controlled.',
      'Stand tall by extending the hips; avoid leaning backward at the top.',
    ],
    imagePaths: ['Romanian_Deadlift/0.jpg', 'Romanian_Deadlift/1.jpg'],
    goals: {TrainingGoal.buildMuscle, TrainingGoal.getStronger},
    defaultSets: 3,
    defaultReps: '6–10 reps',
    restSeconds: 120,
    movementPattern: 'Hip hinge',
    variationGroup: 'hip-hinge',
    coachingCues: ['Push hips backward', 'Keep the weight close to the legs'],
    commonMistakes: ['Turning it into a squat', 'Overextending at lockout'],
  ),
  ExerciseGuide(
    id: 'Standing_Military_Press',
    name: 'Standing overhead press',
    level: 'Beginner',
    equipment: 'Barbell',
    primaryMuscle: 'Shoulders',
    secondaryMuscles: ['Triceps'],
    instructions: [
      'Start with the bar supported near your upper chest and brace your trunk.',
      'Press overhead while keeping the bar path controlled.',
      'Lower slowly to the starting position without overextending your lower back.',
    ],
    imagePaths: [
      'Standing_Military_Press/0.jpg',
      'Standing_Military_Press/1.jpg',
    ],
    goals: {TrainingGoal.buildMuscle, TrainingGoal.getStronger},
    defaultSets: 3,
    defaultReps: '6–10 reps',
    restSeconds: 90,
    movementPattern: 'Vertical push',
    variationGroup: 'overhead-press',
    coachingCues: [
      'Brace before pressing',
      'Finish with the bar over mid-foot',
    ],
    commonMistakes: [
      'Leaning far backward',
      'Pressing around the face in an arc',
    ],
  ),
  ExerciseGuide(
    id: 'Childs_Pose',
    name: "Child's pose",
    level: 'Beginner',
    equipment: 'Bodyweight',
    primaryMuscle: 'Lower back',
    secondaryMuscles: ['Lats'],
    instructions: [
      'Kneel comfortably and sit your hips back toward your heels.',
      'Reach your arms forward and let your chest move gently toward the floor.',
      'Breathe slowly and stay within a comfortable, pain-free range.',
    ],
    imagePaths: ['Childs_Pose/0.jpg', 'Childs_Pose/1.jpg'],
    goals: {TrainingGoal.mobility},
    defaultSets: 2,
    defaultReps: '30–60 sec',
    restSeconds: 30,
    movementPattern: 'Recovery mobility',
    variationGroup: 'spine-mobility',
    coachingCues: ['Use slow breaths', 'Stay in a pain-free range'],
    commonMistakes: [
      'Forcing the hips backward',
      'Holding tension in the neck',
    ],
  ),
  ExerciseGuide(
    id: 'Bodyweight_Squat',
    name: 'Bodyweight squat',
    level: 'Beginner',
    equipment: 'Bodyweight',
    primaryMuscle: 'Quadriceps',
    secondaryMuscles: ['Glutes', 'Hamstrings'],
    instructions: [
      'Stand with feet at a comfortable width and toes turned slightly out.',
      'Sit down between your hips while keeping your chest comfortably tall.',
      'Drive through the whole foot to stand and finish with control.',
    ],
    imagePaths: ['Bodyweight_Squat/0.jpg', 'Bodyweight_Squat/1.jpg'],
    goals: {
      TrainingGoal.loseWeight,
      TrainingGoal.improveFitness,
      TrainingGoal.mobility,
    },
    defaultSets: 3,
    defaultReps: '12–20 reps',
    restSeconds: 45,
    movementPattern: 'Squat',
    variationGroup: 'squat',
    coachingCues: [
      'Reach hips down between the feet',
      'Let knees follow the toes',
    ],
    commonMistakes: ['Heels lifting', 'Knees collapsing inward'],
  ),
  ExerciseGuide(
    id: 'Goblet_Squat',
    name: 'Goblet squat',
    level: 'Beginner',
    equipment: 'Dumbbell or kettlebell',
    primaryMuscle: 'Quadriceps',
    secondaryMuscles: ['Glutes', 'Hamstrings', 'Calves'],
    instructions: [
      'Hold one weight close to your chest and set your feet comfortably.',
      'Brace and squat down while keeping the weight close to your body.',
      'Stand through the whole foot without letting the knees collapse inward.',
    ],
    imagePaths: ['Goblet_Squat/0.jpg', 'Goblet_Squat/1.jpg'],
    goals: {
      TrainingGoal.buildMuscle,
      TrainingGoal.loseWeight,
      TrainingGoal.improveFitness,
    },
    defaultSets: 3,
    defaultReps: '8–15 reps',
    restSeconds: 60,
    movementPattern: 'Squat',
    variationGroup: 'squat',
    coachingCues: [
      'Keep the weight near your sternum',
      'Stay balanced over mid-foot',
    ],
    commonMistakes: [
      'Holding the weight away from the body',
      'Rushing the bottom',
    ],
  ),
  ExerciseGuide(
    id: 'Leg_Press',
    name: 'Leg press',
    level: 'Beginner',
    equipment: 'Leg press machine',
    primaryMuscle: 'Quadriceps',
    secondaryMuscles: ['Glutes', 'Hamstrings', 'Calves'],
    instructions: [
      'Adjust the seat so your hips and back remain supported throughout the movement.',
      'Lower the platform under control to a comfortable depth.',
      'Press through the whole foot without forcefully locking the knees.',
    ],
    imagePaths: ['Leg_Press/0.jpg', 'Leg_Press/1.jpg'],
    goals: {TrainingGoal.buildMuscle, TrainingGoal.getStronger},
    defaultSets: 3,
    defaultReps: '8–15 reps',
    restSeconds: 90,
    movementPattern: 'Squat',
    variationGroup: 'squat',
    coachingCues: [
      'Keep hips against the pad',
      'Use equal pressure through both feet',
    ],
    commonMistakes: [
      'Lowering until the pelvis rolls',
      'Locking knees aggressively',
    ],
  ),
  ExerciseGuide(
    id: 'Dumbbell_Bench_Press',
    name: 'Dumbbell bench press',
    level: 'Beginner',
    equipment: 'Dumbbells and bench',
    primaryMuscle: 'Chest',
    secondaryMuscles: ['Shoulders', 'Triceps'],
    instructions: [
      'Lie securely with feet planted and dumbbells above the chest.',
      'Lower both weights under control with wrists above the elbows.',
      'Press the weights upward without clashing them together.',
    ],
    imagePaths: ['Dumbbell_Bench_Press/0.jpg', 'Dumbbell_Bench_Press/1.jpg'],
    goals: {TrainingGoal.buildMuscle, TrainingGoal.getStronger},
    defaultSets: 3,
    defaultReps: '8–12 reps',
    restSeconds: 75,
    movementPattern: 'Horizontal push',
    variationGroup: 'chest-press',
    coachingCues: [
      'Keep shoulder blades supported',
      'Control both dumbbells evenly',
    ],
    commonMistakes: [
      'Dropping too deep without control',
      'Bending wrists backward',
    ],
  ),
  ExerciseGuide(
    id: 'Incline_Dumbbell_Press',
    name: 'Incline dumbbell press',
    level: 'Beginner',
    equipment: 'Dumbbells and incline bench',
    primaryMuscle: 'Upper chest',
    secondaryMuscles: ['Shoulders', 'Triceps'],
    instructions: [
      'Set a moderate incline and sit with both feet planted.',
      'Lower the dumbbells toward the upper chest with forearms controlled.',
      'Press upward while keeping your shoulders supported by the bench.',
    ],
    imagePaths: [
      'Incline_Dumbbell_Press/0.jpg',
      'Incline_Dumbbell_Press/1.jpg',
    ],
    goals: {TrainingGoal.buildMuscle, TrainingGoal.getStronger},
    defaultSets: 3,
    defaultReps: '8–12 reps',
    restSeconds: 75,
    movementPattern: 'Incline push',
    variationGroup: 'chest-press',
    coachingCues: ['Use a moderate bench angle', 'Keep wrists over elbows'],
    commonMistakes: [
      'Setting the bench nearly vertical',
      'Shrugging toward the ears',
    ],
  ),
  ExerciseGuide(
    id: 'Push_Up_to_Side_Plank',
    name: 'Push-up to side plank',
    level: 'Intermediate',
    equipment: 'Bodyweight',
    primaryMuscle: 'Chest',
    secondaryMuscles: ['Core', 'Shoulders', 'Triceps'],
    instructions: [
      'Perform one controlled push-up from a stable plank.',
      'Rotate onto one hand and the sides of your feet as the other arm reaches upward.',
      'Return to plank, repeat the push-up, and rotate to the other side.',
    ],
    imagePaths: ['Push_Up_to_Side_Plank/0.jpg', 'Push_Up_to_Side_Plank/1.jpg'],
    goals: {TrainingGoal.loseWeight, TrainingGoal.improveFitness},
    defaultSets: 3,
    defaultReps: '6–10 / side',
    restSeconds: 60,
    movementPattern: 'Push and rotate',
    variationGroup: 'chest-press',
    coachingCues: ['Rotate as one unit', 'Keep the supporting shoulder strong'],
    commonMistakes: [
      'Letting hips drop during rotation',
      'Rushing between sides',
    ],
  ),
  ExerciseGuide(
    id: 'Inverted_Row',
    name: 'Inverted row',
    level: 'Beginner',
    equipment: 'Low bar or suspension trainer',
    primaryMuscle: 'Back',
    secondaryMuscles: ['Lats', 'Biceps'],
    instructions: [
      'Set a secure bar and hang beneath it with your body in a straight line.',
      'Pull your chest toward the bar while drawing your shoulders back.',
      'Lower under control without allowing your hips to sag.',
    ],
    imagePaths: ['Inverted_Row/0.jpg', 'Inverted_Row/1.jpg'],
    goals: {
      TrainingGoal.buildMuscle,
      TrainingGoal.getStronger,
      TrainingGoal.improveFitness,
    },
    defaultSets: 3,
    defaultReps: '8–15 reps',
    restSeconds: 60,
    movementPattern: 'Horizontal pull',
    variationGroup: 'horizontal-pull',
    coachingCues: [
      'Keep ribs and hips aligned',
      'Pull the bar toward the lower chest',
    ],
    commonMistakes: [
      'Leading with the chin',
      'Losing the straight body position',
    ],
  ),
  ExerciseGuide(
    id: 'Close-Grip_Front_Lat_Pulldown',
    name: 'Close-grip lat pulldown',
    level: 'Beginner',
    equipment: 'Cable machine',
    primaryMuscle: 'Lats',
    secondaryMuscles: ['Biceps', 'Back', 'Shoulders'],
    instructions: [
      'Secure your thighs beneath the pad and take a comfortable close grip.',
      'Pull the handle toward the upper chest while keeping the torso steady.',
      'Return slowly until the arms are long and the shoulders remain controlled.',
    ],
    imagePaths: [
      'Close-Grip_Front_Lat_Pulldown/0.jpg',
      'Close-Grip_Front_Lat_Pulldown/1.jpg',
    ],
    goals: {TrainingGoal.buildMuscle, TrainingGoal.getStronger},
    defaultSets: 3,
    defaultReps: '8–12 reps',
    restSeconds: 75,
    movementPattern: 'Vertical pull',
    variationGroup: 'vertical-pull',
    coachingCues: [
      'Keep chest comfortably tall',
      'Drive elbows toward your sides',
    ],
    commonMistakes: ['Pulling behind the neck', 'Using large body swings'],
  ),
  ExerciseGuide(
    id: 'Barbell_Deadlift',
    name: 'Barbell deadlift',
    level: 'Intermediate',
    equipment: 'Barbell',
    primaryMuscle: 'Posterior chain',
    secondaryMuscles: ['Glutes', 'Hamstrings', 'Back', 'Quadriceps'],
    instructions: [
      'Stand with the bar over mid-foot and take a secure grip.',
      'Brace, keep the bar close, and push the floor away to stand.',
      'Return the bar by sending the hips back before bending the knees.',
    ],
    imagePaths: ['Barbell_Deadlift/0.jpg', 'Barbell_Deadlift/1.jpg'],
    goals: {TrainingGoal.buildMuscle, TrainingGoal.getStronger},
    defaultSets: 3,
    defaultReps: '3–6 reps',
    restSeconds: 150,
    movementPattern: 'Hip hinge',
    variationGroup: 'hip-hinge',
    coachingCues: [
      'Brace before the bar leaves the floor',
      'Keep the bar close',
    ],
    commonMistakes: [
      'Jerking the bar from the floor',
      'Leaning backward at the top',
    ],
  ),
  ExerciseGuide(
    id: 'Butt_Lift_Bridge',
    name: 'Glute bridge',
    level: 'Beginner',
    equipment: 'Bodyweight',
    primaryMuscle: 'Glutes',
    secondaryMuscles: ['Hamstrings'],
    instructions: [
      'Lie on your back with knees bent and feet planted.',
      'Brace gently and lift the hips by squeezing the glutes.',
      'Pause briefly, then lower under control without overextending the back.',
    ],
    imagePaths: ['Butt_Lift_Bridge/0.jpg', 'Butt_Lift_Bridge/1.jpg'],
    goals: {
      TrainingGoal.buildMuscle,
      TrainingGoal.improveFitness,
      TrainingGoal.mobility,
    },
    defaultSets: 3,
    defaultReps: '12–20 reps',
    restSeconds: 45,
    movementPattern: 'Hip extension',
    variationGroup: 'hip-extension',
    coachingCues: ['Drive through the heels', 'Finish by squeezing the glutes'],
    commonMistakes: [
      'Arching the lower back',
      'Pushing mainly through the toes',
    ],
  ),
  ExerciseGuide(
    id: 'Dumbbell_Shoulder_Press',
    name: 'Dumbbell shoulder press',
    level: 'Intermediate',
    equipment: 'Dumbbells',
    primaryMuscle: 'Shoulders',
    secondaryMuscles: ['Triceps'],
    instructions: [
      'Start seated or standing with dumbbells near shoulder height.',
      'Brace and press both weights overhead along a controlled path.',
      'Lower to the start without leaning backward or dropping the weights.',
    ],
    imagePaths: [
      'Dumbbell_Shoulder_Press/0.jpg',
      'Dumbbell_Shoulder_Press/1.jpg',
    ],
    goals: {TrainingGoal.buildMuscle, TrainingGoal.getStronger},
    defaultSets: 3,
    defaultReps: '8–12 reps',
    restSeconds: 75,
    movementPattern: 'Vertical push',
    variationGroup: 'overhead-press',
    coachingCues: [
      'Keep ribs stacked',
      'Finish with weights above the shoulders',
    ],
    commonMistakes: ['Overarching the lower back', 'Shrugging throughout'],
  ),
  ExerciseGuide(
    id: 'Hammer_Curls',
    name: 'Hammer curls',
    level: 'Beginner',
    equipment: 'Dumbbells',
    primaryMuscle: 'Biceps',
    secondaryMuscles: ['Forearms'],
    instructions: [
      'Stand tall with palms facing inward and arms by your sides.',
      'Curl the dumbbells without moving your upper arms forward.',
      'Lower fully under control before starting the next repetition.',
    ],
    imagePaths: ['Hammer_Curls/0.jpg', 'Hammer_Curls/1.jpg'],
    goals: {TrainingGoal.buildMuscle},
    defaultSets: 3,
    defaultReps: '10–15 reps',
    restSeconds: 45,
    movementPattern: 'Elbow flexion',
    variationGroup: 'arm-curl',
    coachingCues: ['Keep wrists neutral', 'Keep elbows near your sides'],
    commonMistakes: ['Swinging the torso', 'Cutting the lowering phase short'],
  ),
  ExerciseGuide(
    id: 'Dips_-_Triceps_Version',
    name: 'Triceps dips',
    level: 'Intermediate',
    equipment: 'Parallel bars',
    primaryMuscle: 'Triceps',
    secondaryMuscles: ['Chest', 'Shoulders'],
    instructions: [
      'Support yourself securely on parallel bars with shoulders controlled.',
      'Bend the elbows and lower only through a comfortable shoulder range.',
      'Press back to the top without forcefully locking the elbows.',
    ],
    imagePaths: [
      'Dips_-_Triceps_Version/0.jpg',
      'Dips_-_Triceps_Version/1.jpg',
    ],
    goals: {TrainingGoal.buildMuscle, TrainingGoal.getStronger},
    defaultSets: 3,
    defaultReps: '6–12 reps',
    restSeconds: 75,
    movementPattern: 'Vertical push',
    variationGroup: 'triceps-press',
    coachingCues: ['Keep shoulders away from ears', 'Use a pain-free depth'],
    commonMistakes: ['Dropping too deep', 'Letting shoulders roll forward'],
  ),
  ExerciseGuide(
    id: 'Crunches',
    name: 'Crunches',
    level: 'Beginner',
    equipment: 'Bodyweight',
    primaryMuscle: 'Core',
    secondaryMuscles: [],
    instructions: [
      'Lie with knees bent, feet planted, and hands lightly supporting the head.',
      'Lift the shoulder blades by shortening the distance between ribs and pelvis.',
      'Lower slowly while keeping the neck relaxed.',
    ],
    imagePaths: ['Crunches/0.jpg', 'Crunches/1.jpg'],
    goals: {TrainingGoal.buildMuscle, TrainingGoal.improveFitness},
    defaultSets: 3,
    defaultReps: '12–20 reps',
    restSeconds: 45,
    movementPattern: 'Core flexion',
    variationGroup: 'core-flexion',
    coachingCues: [
      'Lead with the ribs',
      'Keep the movement small and controlled',
    ],
    commonMistakes: ['Pulling the neck', 'Using momentum'],
  ),
  ExerciseGuide(
    id: 'Hanging_Leg_Raise',
    name: 'Hanging leg raise',
    level: 'Advanced',
    equipment: 'Pull-up bar',
    primaryMuscle: 'Core',
    secondaryMuscles: ['Hip flexors', 'Forearms'],
    instructions: [
      'Hang securely and settle the body before beginning.',
      'Raise bent knees or straight legs by curling the pelvis upward.',
      'Lower slowly and stop any swing before the next repetition.',
    ],
    imagePaths: ['Hanging_Leg_Raise/0.jpg', 'Hanging_Leg_Raise/1.jpg'],
    goals: {TrainingGoal.buildMuscle, TrainingGoal.getStronger},
    defaultSets: 3,
    defaultReps: '6–12 reps',
    restSeconds: 60,
    movementPattern: 'Core flexion',
    variationGroup: 'core-flexion',
    coachingCues: [
      'Curl the pelvis, not only the legs',
      'Reset the swing each rep',
    ],
    commonMistakes: ['Using momentum', 'Dropping the legs quickly'],
  ),
  ExerciseGuide(
    id: 'Side_Bridge',
    name: 'Side plank',
    level: 'Beginner',
    equipment: 'Bodyweight',
    primaryMuscle: 'Core',
    secondaryMuscles: ['Shoulders', 'Glutes'],
    instructions: [
      'Place the elbow beneath the shoulder and stack or stagger the feet.',
      'Lift the hips until the body forms a straight line from head to feet.',
      'Breathe steadily and finish when the position can no longer be held cleanly.',
    ],
    imagePaths: ['Side_Bridge/0.jpg', 'Side_Bridge/1.jpg'],
    goals: {TrainingGoal.improveFitness, TrainingGoal.mobility},
    defaultSets: 3,
    defaultReps: '20–40 sec / side',
    restSeconds: 45,
    movementPattern: 'Core stability',
    variationGroup: 'core-stability',
    coachingCues: ['Push the floor away', 'Keep hips stacked'],
    commonMistakes: ['Shoulder collapsing', 'Hips rotating toward the floor'],
  ),
  ExerciseGuide(
    id: 'Rope_Jumping',
    name: 'Jump rope',
    level: 'Intermediate',
    equipment: 'Jump rope',
    primaryMuscle: 'Conditioning',
    secondaryMuscles: ['Calves', 'Quadriceps', 'Hamstrings'],
    instructions: [
      'Stand tall with the rope behind you and elbows near your sides.',
      'Turn the rope mainly from the wrists and use small relaxed jumps.',
      'Land softly and stop before your rhythm or posture breaks down.',
    ],
    imagePaths: ['Rope_Jumping/0.jpg', 'Rope_Jumping/1.jpg'],
    goals: {TrainingGoal.loseWeight, TrainingGoal.improveFitness},
    defaultSets: 4,
    defaultReps: '30–60 sec',
    restSeconds: 30,
    movementPattern: 'Conditioning',
    variationGroup: 'conditioning',
    coachingCues: ['Use quiet, low jumps', 'Turn from the wrists'],
    commonMistakes: ['Jumping too high', 'Swinging the arms widely'],
  ),
  ExerciseGuide(
    id: 'Leg_Extensions',
    name: 'Leg extension',
    level: 'Beginner',
    equipment: 'Leg extension machine',
    primaryMuscle: 'Quadriceps',
    secondaryMuscles: [],
    instructions: [
      'Adjust the seat and shin pad so the machine aligns comfortably with your knee.',
      'Extend the knees smoothly without kicking the weight.',
      'Pause briefly, then lower the stack under control.',
    ],
    imagePaths: ['Leg_Extensions/0.jpg', 'Leg_Extensions/1.jpg'],
    goals: {TrainingGoal.buildMuscle},
    defaultSets: 3,
    defaultReps: '10–15 reps',
    restSeconds: 60,
    movementPattern: 'Knee extension',
    variationGroup: 'knee-extension',
    coachingCues: [
      'Keep hips against the seat',
      'Control the final few degrees',
    ],
    commonMistakes: ['Using momentum', 'Letting the weight stack slam'],
  ),
  ExerciseGuide(
    id: 'Seated_Leg_Curl',
    name: 'Seated leg curl',
    level: 'Beginner',
    equipment: 'Leg curl machine',
    primaryMuscle: 'Hamstrings',
    secondaryMuscles: [],
    instructions: [
      'Adjust the backrest and pads so the knee aligns with the machine pivot.',
      'Curl the pad down and back using the hamstrings.',
      'Return slowly without allowing the weight stack to slam.',
    ],
    imagePaths: ['Seated_Leg_Curl/0.jpg', 'Seated_Leg_Curl/1.jpg'],
    goals: {TrainingGoal.buildMuscle},
    defaultSets: 3,
    defaultReps: '10–15 reps',
    restSeconds: 60,
    movementPattern: 'Knee flexion',
    variationGroup: 'knee-flexion',
    coachingCues: ['Keep hips against the seat', 'Squeeze without jerking'],
    commonMistakes: ['Lifting the hips', 'Releasing the weight too quickly'],
  ),
  ExerciseGuide(
    id: 'Standing_Dumbbell_Calf_Raise',
    name: 'Standing calf raise',
    level: 'Beginner',
    equipment: 'Dumbbells and step',
    primaryMuscle: 'Calves',
    secondaryMuscles: [],
    instructions: [
      'Stand securely with the balls of your feet on a step and hold support if needed.',
      'Rise onto the toes and pause briefly at the top.',
      'Lower the heels through a comfortable range under control.',
    ],
    imagePaths: [
      'Standing_Dumbbell_Calf_Raise/0.jpg',
      'Standing_Dumbbell_Calf_Raise/1.jpg',
    ],
    goals: {TrainingGoal.buildMuscle, TrainingGoal.improveFitness},
    defaultSets: 3,
    defaultReps: '12–20 reps',
    restSeconds: 45,
    movementPattern: 'Calf raise',
    variationGroup: 'calf-raise',
    coachingCues: ['Pause at the top', 'Use a controlled stretch'],
    commonMistakes: ['Bouncing rapidly', 'Rolling ankles outward'],
  ),
  ExerciseGuide(
    id: 'Cat_Stretch',
    name: 'Cat stretch',
    level: 'Beginner',
    equipment: 'Bodyweight',
    primaryMuscle: 'Spine',
    secondaryMuscles: ['Upper back', 'Lower back'],
    instructions: [
      'Start on hands and knees with wrists beneath shoulders and knees beneath hips.',
      'Exhale and gently round the spine while letting the head follow naturally.',
      'Return toward neutral slowly rather than forcing the opposite position.',
    ],
    imagePaths: ['Cat_Stretch/0.jpg', 'Cat_Stretch/1.jpg'],
    goals: {TrainingGoal.mobility},
    defaultSets: 2,
    defaultReps: '6–10 slow reps',
    restSeconds: 20,
    movementPattern: 'Recovery mobility',
    variationGroup: 'spine-mobility',
    coachingCues: [
      'Move one segment at a time',
      'Match the movement to your breath',
    ],
    commonMistakes: ['Forcing the neck', 'Moving quickly through discomfort'],
  ),
  ExerciseGuide(
    id: 'Kneeling_Hip_Flexor',
    name: 'Kneeling hip-flexor stretch',
    level: 'Beginner',
    equipment: 'Bodyweight',
    primaryMuscle: 'Hip flexors',
    secondaryMuscles: ['Quadriceps'],
    instructions: [
      'Kneel on a padded surface with the other foot in front.',
      'Gently tuck the pelvis and shift forward until the front of the rear hip stretches.',
      'Stay tall, breathe slowly, and repeat on the other side.',
    ],
    imagePaths: ['Kneeling_Hip_Flexor/0.jpg', 'Kneeling_Hip_Flexor/1.jpg'],
    goals: {TrainingGoal.mobility},
    defaultSets: 2,
    defaultReps: '30–45 sec / side',
    restSeconds: 20,
    movementPattern: 'Recovery mobility',
    variationGroup: 'hip-mobility',
    coachingCues: ['Tuck the pelvis gently', 'Stay tall'],
    commonMistakes: ['Arching the lower back', 'Lunging too far forward'],
  ),
  ExerciseGuide(
    id: 'Hamstring_Stretch',
    name: 'Hamstring stretch',
    level: 'Beginner',
    equipment: 'Bodyweight',
    primaryMuscle: 'Hamstrings',
    secondaryMuscles: [],
    instructions: [
      'Set up in the shown position with the working leg comfortably extended.',
      'Hinge gently from the hips until the back of the thigh stretches.',
      'Hold without bouncing, breathe normally, and switch sides.',
    ],
    imagePaths: ['Hamstring_Stretch/0.jpg', 'Hamstring_Stretch/1.jpg'],
    goals: {TrainingGoal.mobility},
    defaultSets: 2,
    defaultReps: '30–45 sec / side',
    restSeconds: 20,
    movementPattern: 'Recovery mobility',
    variationGroup: 'posterior-mobility',
    coachingCues: ['Hinge from the hips', 'Keep the stretch gentle'],
    commonMistakes: ['Bouncing', 'Rounding aggressively to reach farther'],
  ),
];

List<ExerciseGuide> exercisesForGoal(TrainingGoal goal, {int? limit}) {
  final matches = exerciseGuides
      .where((exercise) => exercise.goals.contains(goal))
      .toList(growable: false);
  if (limit == null || matches.length <= limit) return matches;
  return matches.take(limit).toList(growable: false);
}

List<ExerciseGuide> variationsFor(ExerciseGuide exercise) {
  final group = exercise.variationGroup;
  if (group == null) return const [];
  return exerciseGuides
      .where(
        (candidate) =>
            candidate.id != exercise.id && candidate.variationGroup == group,
      )
      .toList(growable: false);
}
