// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1kkvEhiRF8zOVlnrOcDjnlO703i1ii80',
    appId: '1:818455248956:web:3e5c0a6f6ad25621ae8339',
    messagingSenderId: '818455248956',
    projectId: 'recipe-app-cdeef',
    authDomain: 'recipe-app-cdeef.firebaseapp.com',
    storageBucket: 'recipe-app-cdeef.appspot.com',
    measurementId: 'G-YC7627RDKF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAt3v7ZVU8y96UyB5aAxFuw5n09ZnSsHAY',
    appId: '1:818455248956:android:2af4befd8c93277bae8339',
    messagingSenderId: '818455248956',
    projectId: 'recipe-app-cdeef',
    storageBucket: 'recipe-app-cdeef.appspot.com',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6UBjNwB0Ainl62gPdFbtbn0WNzvCwkQo',
    appId: '1:818455248956:ios:d69ec43c8948da91ae8339',
    messagingSenderId: '818455248956',
    projectId: 'recipe-app-cdeef',
    storageBucket: 'recipe-app-cdeef.appspot.com',
    iosBundleId: 'com.rishva.gymmanagement',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6UBjNwB0Ainl62gPdFbtbn0WNzvCwkQo',
    appId: '1:818455248956:ios:d69ec43c8948da91ae8339',
    messagingSenderId: '818455248956',
    projectId: 'recipe-app-cdeef',
    storageBucket: 'recipe-app-cdeef.appspot.com',
    iosBundleId: 'com.rishva.gymmanagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1kkvEhiRF8zOVlnrOcDjnlO703i1ii80',
    appId: '1:818455248956:web:90eb94b8b8717b87ae8339',
    messagingSenderId: '818455248956',
    projectId: 'recipe-app-cdeef',
    authDomain: 'recipe-app-cdeef.firebaseapp.com',
    storageBucket: 'recipe-app-cdeef.appspot.com',
    measurementId: 'G-FQ609JKQ9D',
  );
}
