// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1M3pF7VvrGQt2uI3Ao31DPIabgMoxil4',
    appId: '1:996305810467:web:b20ab104434075da7bad96',
    messagingSenderId: '996305810467',
    projectId: 'createmix-in',
    authDomain: 'createmix-in.firebaseapp.com',
    storageBucket: 'createmix-in.firebasestorage.app',
    measurementId: 'G-RQ0WD1YM3B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQfdRGRV6G9bTcFW72GvH9IANZQfz1-Ys',
    appId: '1:996305810467:android:56c3f9c7cff8cfa27bad96',
    messagingSenderId: '996305810467',
    projectId: 'createmix-in',
    storageBucket: 'createmix-in.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDw8S3oON2LTj_5hC0Cd983du7w1tjF1mA',
    appId: '1:996305810467:ios:1d9a9c1cdc384c8e7bad96',
    messagingSenderId: '996305810467',
    projectId: 'createmix-in',
    storageBucket: 'createmix-in.firebasestorage.app',
    iosBundleId: 'com.rishva.gymmanagement',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDw8S3oON2LTj_5hC0Cd983du7w1tjF1mA',
    appId: '1:996305810467:ios:1d9a9c1cdc384c8e7bad96',
    messagingSenderId: '996305810467',
    projectId: 'createmix-in',
    storageBucket: 'createmix-in.firebasestorage.app',
    iosBundleId: 'com.rishva.gymmanagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1M3pF7VvrGQt2uI3Ao31DPIabgMoxil4',
    appId: '1:996305810467:web:94b70b5a5c2f885f7bad96',
    messagingSenderId: '996305810467',
    projectId: 'createmix-in',
    authDomain: 'createmix-in.firebaseapp.com',
    storageBucket: 'createmix-in.firebasestorage.app',
    measurementId: 'G-JCE9ZENGGH',
  );
}
