import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';

enum AppFlavor { development, staging, production }

class AppEnvironment {
  const AppEnvironment._();

  static const flavorName = String.fromEnvironment(
    'APP_FLAVOR',
    defaultValue: 'development',
  );
  static const useEmulators = bool.fromEnvironment(
    'USE_FIREBASE_EMULATORS',
    defaultValue: false,
  );
  static const emulatorHostOverride = String.fromEnvironment('EMULATOR_HOST');
  static const _projectIdOverride = String.fromEnvironment(
    'FIREBASE_PROJECT_ID',
  );

  static AppFlavor get flavor => switch (flavorName) {
    'production' => AppFlavor.production,
    'staging' => AppFlavor.staging,
    _ => AppFlavor.development,
  };

  static bool get hasFirebaseOverride => _projectIdOverride.isNotEmpty;

  static String get projectId =>
      _projectIdOverride.isEmpty ? 'demo-gym-dev' : _projectIdOverride;
  static String get apiKey => const String.fromEnvironment(
    'FIREBASE_API_KEY',
    defaultValue: 'demo-api-key',
  );
  static String get appId {
    if (kIsWeb) {
      return const String.fromEnvironment(
        'FIREBASE_WEB_APP_ID',
        defaultValue: '1:1234567890:web:demo-gym-dev',
      );
    }
    if (defaultTargetPlatform == TargetPlatform.iOS ||
        defaultTargetPlatform == TargetPlatform.macOS) {
      return const String.fromEnvironment(
        'FIREBASE_IOS_APP_ID',
        defaultValue: '1:1234567890:ios:demo-gym-dev',
      );
    }
    if (defaultTargetPlatform == TargetPlatform.windows) {
      return const String.fromEnvironment(
        'FIREBASE_WINDOWS_APP_ID',
        defaultValue: '1:1234567890:web:demo-gym-dev-windows',
      );
    }
    return const String.fromEnvironment(
      'FIREBASE_ANDROID_APP_ID',
      defaultValue: '1:1234567890:android:demo-gym-dev',
    );
  }

  static String get messagingSenderId => const String.fromEnvironment(
    'FIREBASE_MESSAGING_SENDER_ID',
    defaultValue: '1234567890',
  );
  static String get storageBucket => const String.fromEnvironment(
    'FIREBASE_STORAGE_BUCKET',
    defaultValue: 'demo-gym-dev.appspot.com',
  );
  static String get webAppCheckSiteKey =>
      // The development Firebase project is the checked-in default. This is a
      // public reCAPTCHA Enterprise site key, not a credential; without it a
      // direct `flutter run -d chrome` sends no App Check token and every
      // App-Check-enforced callable is rejected after sign-in.
      const String.fromEnvironment(
        'FIREBASE_APPCHECK_SITE_KEY',
        defaultValue: '6LddO5otAAAAANe-6ZBAhGUrt87kjNLqiXbbfx8o',
      );

  /// Used by the Emulator Suite and by explicit staging/production
  /// `--dart-define` overrides. Normal development uses the platform-specific
  /// options generated by FlutterFire in `firebase_options.dart`.
  static FirebaseOptions get firebaseOptions => FirebaseOptions(
    apiKey: apiKey,
    appId: appId,
    messagingSenderId: messagingSenderId,
    projectId: projectId,
    storageBucket: storageBucket,
    authDomain: kIsWeb ? '$projectId.firebaseapp.com' : null,
    iosBundleId:
        !kIsWeb &&
            (defaultTargetPlatform == TargetPlatform.iOS ||
                defaultTargetPlatform == TargetPlatform.macOS)
        ? 'com.rishva.gymmanagement'
        : null,
  );

  static String get emulatorHost {
    if (emulatorHostOverride.isNotEmpty) return emulatorHostOverride;
    if (kIsWeb) return '127.0.0.1';
    return defaultTargetPlatform == TargetPlatform.android
        ? '10.0.2.2'
        : '127.0.0.1';
  }
}
